### ISSUE TITLE
Tag 0.0.1 does not include registration.php file

### ISSUE THREAD

**Issue by thanasisgalanis** [astorm/magento2-tutorial-objectpreference1#1]
In [this article](http://alanstorm.com/magento_2_object_manager_preferences/) you have a link to the module's ["latest release"](https://github.com/astorm/magento2-tutorial-objectpreference1/releases) page. However tag 0.0.1 (the latest realese so far), does not include registration.php file.

**Comment by astorm** [comment]
Pushed tag 0.0.2.  Thanks again!
